#!/bin/bash
echo "Directory:"; pwd 

while true
do 
	echo "Enter file name: "
	read 
	name=$PWD/$REPLY
	if [ ! -f $name ] 
	then 
		echo "file not found"
	else 
		echo "Enter user name" 
		read username

		rules="stat -c %$username $name"
		eval $rules
	fi


	while : 
	do  
		echo "Prodolgyt?(y/n)"
		read cont 
		if test $cont = "y"; then
			echo 
			break
		elif test $cont = "n"; then
			echo "Close" 
			exit
		else 
			echo "Input Error"
		fi
	done
done 

