#!/bin/bash
echo "Directory:"; pwd 

while true
do 
	echo "Введите имя файла "
	read file
	if [ ! -f $file ] 
	then 
		echo "Файл не найден"
	else 
		echo "Введите имя пользователя" 
		read username
		usr="user:"$username":"
		echo "У пользователя $username на $file следующие права: "$(getfacl "$file" | grep "$username" | sed  "s/${usr}//g")
	fi


	while : 
	do  
		echo "Продолжить?(y/n)"
		read cont 
		if test $cont = "y"; then
			echo 
			break
		elif test $cont = "n"; then
			echo "Выход" 
			exit
		else 
			echo "Некорректный ввод"
		fi
	done
done 

